apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-1
  template:
    metadata:
      labels:
        name: nginx-1
    spec:
      containers:
      - name: nginx
        image: gcr.io/${project}/nginx:latest
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 90
          periodSeconds: 10