---
- hosts: localhost
  become: true
  vars_files: /workdir/ansible/vars.yml
  tasks:
    - import_tasks: /workdir/ansible/maven.yml
    - import_tasks: /workdir/ansible/sonarqube.yml
    - import_tasks: /workdir/ansible/jenkins.yml
    - import_tasks: /workdir/ansible/firewall_web.yml
    - import_tasks: /workdir/ansible/firewall_sonar.yml
    - import_tasks: /workdir/ansible/docker.yml
...